# Generated by Django 4.0.2 on 2022-07-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_marks',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='student_marks',
            name='stubject',
        ),
        migrations.AddField(
            model_name='student_marks',
            name='biology',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='english',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='hindi',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='maths',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='physic',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='sanskrit',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='social',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='telugu',
            field=models.TextField(blank=True),
        ),
    ]
