# Generated by Django 4.0.2 on 2022-07-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_student_marks_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_marks',
            name='percent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='total',
            field=models.TextField(blank=True),
        ),
    ]
