# Generated by Django 4.0.2 on 2022-07-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_marks_percent_student_marks_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_marks',
            name='ba',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ea',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ha',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ma',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='pa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='sa',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='sana',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='student_marks',
            name='ta',
            field=models.TextField(blank=True),
        ),
    ]
