# Generated by Django 4.0.2 on 2022-07-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student_marks_ba_student_marks_ea_student_marks_ha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_marks',
            name='t_p',
            field=models.TextField(blank=True),
        ),
    ]
